### ISSUE TITLE
Issues with the JavaScript spec tests

### ISSUE THREAD

**Issue by jakobkummerow** [WebAssembly/function-references#100] opened 2023-07-07 14:35 UTC
I've run the current version of the JavaScript tests in this repo in V8, and encountered a couple of issues.

(1) The (generated?) function `assert_return()` has a bug in the `"ref.null"` case, where it treats `actual` as a scalar value, but it's actually an array (see other `case`s in the same `switch` for comparison). In other words, in the snippet:
```
case "ref.null":
        if (actual !== null) {
          throw new Error("Wasm null return value expected, got " + actual);
        };
```
both occurrences of `actual` should be `actual[i]`.
This makes the following tests fail:
- ref_null
- select
- table

(2) There are a few tests that require `global.get $non-imported-constant-global` to be a "constant expression" that can be used to initialize other globals, but that's a change we made [in the GC proposal](https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md#constant-expressions), not here. (It's also not a big deal for any implementations that are planning to ship function-references and GC at the same time.) This affects the following tests:
- data
- elem
- global

(3) The test `type-equivalence` [asserts](https://github.com/WebAssembly/function-references/blob/main/test/core/type-equivalence.wast#L32C5-L32C39) that `(type $t (func (result (ref $t))))` is an invalid type definition, i.e. a type cannot refer to itself. However, if I'm not mistaken, we have decided that standalone type definitions are interpreted as being in an implicit single-entry recgroup, which means that they _can_ refer to themselves.

**Comment by rossberg** [comment] 2023-07-11 08:04
Thanks for looking into this!

(1) That bug seems to have snuck in during some merge, fixed now.

(2) Good point, this should be rectified, either by moving the tests, or by moving the feature.

(3) That's working as intended: This proposal does not yet introduce recursive types (GC does), so can't allow that.

**Comment by jakobkummerow** [comment] 2023-07-11 08:07
Re (3): Fair, but that does mean that the test will need changing (or deleting) once both funcref and GC are merged into the main spec.

**Comment by rossberg** [comment] 2023-07-11 08:21
Yes, effectively, the downstream GC repo already does that.

**Comment by rossberg** [comment] 2023-07-12 06:35
I removed the tests using non imported globals from this repo, they now only appear in the GC repo. Closing this issue.

**Closed by rossberg** 2023-07-12 06:35 UTC
